"""products

Cria o catálogo de Produtos (fora do escopo original da seção 8, adicionado
para tirar a ambiguidade de `schedule_items.quantity` — antes um número sem
unidade declarada em lugar nenhum da UI) e o vínculo opcional `schedule_
items.product_id`. Segue o mesmo padrão de seed de permissões da 0001:
`products.view`/`products.manage`, concedidas aos mesmos papéis que já
gerenciam os outros cadastros (ver `_ROLE_PERMISSION_CODES` em 0001 para o
motivo de OPERADOR ficar de fora).

Revision ID: 5097ad520a5d
Revises: 5c82cbb37726
Create Date: 2026-09-04 14:27:27.160727
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column


# revision identifiers, used by Alembic.
revision: str = '5097ad520a5d'
down_revision: Union[str, None] = '5c82cbb37726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('unit_of_measure', sa.Enum('UNIDADE', 'KG', 'TONELADA', 'LITRO', 'CAIXA', 'PALETE', 'METRO_CUBICO', name='unitofmeasure_enum', native_enum=False, length=20), nullable=False),
    sa.Column('default_weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='productstatus_enum', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    # `(CURRENT_TIMESTAMP)`, não `now()` — a mesma convenção da 0001, porque
    # `now()` é sintaxe MySQL e não roda no SQLite que os testes usam.
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    # `batch_alter_table`, não `add_column`/`create_foreign_key` soltos: o
    # SQLite (usado pelos testes) não suporta `ALTER TABLE ... ADD CONSTRAINT`
    # — o modo batch do Alembic recria a tabela por baixo dos panos só nesse
    # dialeto; no MySQL roda como um ALTER TABLE normal, sem diferença.
    with op.batch_alter_table('schedule_items') as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(
            'fk_schedule_items_product_id', 'products', ['product_id'], ['id'], ondelete='SET NULL',
        )
    # ### end Alembic commands ###

    # --- Seed das novas permissões (mesmo padrão da 0001) ---
    permissions_t = table("permissions", column("id", sa.BigInteger), column("code", sa.String),
                           column("description", sa.String))
    role_permissions_t = table("role_permissions", column("role_id", sa.BigInteger),
                                column("permission_id", sa.BigInteger))

    op.bulk_insert(
        permissions_t,
        [
            {"id": 26, "code": "products.view", "description": "Consultar produtos"},
            {"id": 27, "code": "products.manage", "description": "Criar, editar e remover produtos"},
        ],
    )
    # role ids da 0001: 1=SUPER_ADMIN 2=ADMIN_EMPRESA 3=SUPERVISOR 4=OPERADOR 5=VISUALIZADOR
    op.bulk_insert(
        role_permissions_t,
        [
            {"role_id": 1, "permission_id": 26}, {"role_id": 1, "permission_id": 27},  # SUPER_ADMIN
            {"role_id": 2, "permission_id": 26}, {"role_id": 2, "permission_id": 27},  # ADMIN_EMPRESA
            {"role_id": 3, "permission_id": 26},  # SUPERVISOR (só consulta)
            {"role_id": 5, "permission_id": 26},  # VISUALIZADOR (só consulta)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_items') as batch_op:
        batch_op.drop_constraint('fk_schedule_items_product_id', type_='foreignkey')
        batch_op.drop_column('product_id')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
